Dashboard/urls.py
from django.conf.urls import url
from . import views

app_name = 'detection'

urlpatterns = [
    url(r'^home$', views.homepage, name='homepage'),
    url(r'^violation$', views.violation, name='violation'),
    url(r'^daywise$', views.daywise, name='daywise'),
    url(r'^monitoring$', views.monitoring, name='monitoring'),
]

TVD/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from Dashboard import views
from django.conf.urls.static import static
from django.conf import settings
from Dashboard.tasks import vehicle_detection

from Dashboard.models import Input

urlpatterns = [
                  url('admin/', admin.site.urls),
                  url('', include('Dashboard.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

all_input = Input.objects.filter(is_processed=False)
for each_input in all_input:
    # vehicle_detection.apply_async(args=[str(each_input.pk)], queue='vehicle_detection')
    vehicle_detection(str(each_input.pk))

Dashboard/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


def vehicle_detection_directory(instance, filename):
    return 'Vehicle/{0}/{1}.png'.format(instance.vehicle_type.type, filename)


def vehicle_monitor_directory(instance, filename):
    return 'Vehicle/{0}/{1}'.format(instance.number_detection.number_plate, filename)


def model_directory(instance, filename):
    return 'Model/{0}/{1}'.format(instance.model_type, filename)


def label_directory(instance, filename):
    return 'Label/{0}/{1}'.format(instance.model_type, filename)


def input_video_directory(instance, filename):
    return 'Input/{0}'.format(filename)


def number_plate_directory(instance, filename):
    return 'Number_Plate/{0}'.format(filename)


class Model(models.Model):
    model_type = models.CharField(max_length=100)
    model = models.FileField(max_length=1000, upload_to=model_directory)
    label = models.FileField(max_length=1000, upload_to=label_directory)
    model_name = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)


class CameraMaster(models.Model):
    location = models.CharField(max_length=100)
    description = models.CharField(max_length=200)
    serial_number = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.serial_number + ' - ' + self.location


class VehicleTypeMaster(models.Model):
    type = models.CharField(max_length=15)
    # number = models.CharField(max_length=15, null=True, blank=True)
    # mobile = models.PositiveIntegerField(default='8554951545')
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.type


class VehicleDetection(models.Model):
    # vehicle = models.ForeignKey(VehicleMaster, on_delete=models.CASCADE)
    # address = models.CharField(max_length=250, default='test')
    vehicle_type = models.ForeignKey(VehicleTypeMaster, on_delete=models.CASCADE)
    camera = models.ForeignKey(CameraMaster, on_delete=models.CASCADE)
    image = models.FileField(upload_to=vehicle_detection_directory, max_length=1000)
    is_processed = models.BooleanField(default=False)
    original_frame = models.CharField(max_length=5000, default='')

    def __str__(self):
        return str(type) + str(self.camera)

    def call_helmet_detection(self):
        # self.save()
        from Dashboard.tasks import number_plate_detection
        monitor_obj_id = number_plate_detection(self.pk)
        if self.vehicle_type.type == 'motorcycle':
            from Dashboard.tasks import helmet_detection
            helmet_detection(self.pk, monitor_obj_id)
def vehicle_detection_saved(sender, instance, *args, **kwargs):
    instance.call_helmet_detection()

post_save.connect(vehicle_detection_saved, sender=VehicleDetection)

class NumberPlate(models.Model):
    number = models.CharField(max_length=15)

    def __str__(self):
        return self.number


class NumberPlateDetection(models.Model):
    number_plate = models.ForeignKey(NumberPlate, on_delete=models.CASCADE, null=True)
    image = models.FileField(upload_to=number_plate_directory, max_length=1000)
    vehicle_detection = models.ForeignKey(VehicleDetection, on_delete=models.CASCADE)

    # def __str__(self):
    #     return self.number_plate


class Input(models.Model):
    file = models.FileField(max_length=1000, upload_to=input_video_directory)
    name = models.CharField(max_length=200, unique=True)
    file_type = models.CharField(max_length=50)
    is_active = models.BooleanField(default=True)
    is_processed = models.BooleanField(default=False)
    camera = models.ForeignKey(CameraMaster, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def call_vehicle_detection(self):
        from Dashboard.tasks import vehicle_detection
        # vehicle_detection.apply_async(args=[str(self.pk)], queue='vehicle_detection')
        print(self.pk)
        vehicle_detection(str(self.pk))

def input_saved(sender, instance, *args, **kwargs):
    instance.call_vehicle_detection()

post_save.connect(input_saved, sender=Input)

class VehicleMonitor(models.Model):
    number_detection = models.ForeignKey(NumberPlateDetection, on_delete=models.CASCADE)
    mobile = models.PositiveIntegerField(default='8554951545')
    timestamp = models.DateTimeField()
    # address = models.CharField(max_length=250, default='test')
    # vehicle_type = models.ForeignKey(VehicleTypeMaster, on_delete=models.CASCADE)
    image = models.FileField(max_length=1000, upload_to=vehicle_monitor_directory)

    # is_done = models.BooleanField(default=False)

    def __str__(self):
        return str(self.number_detection)


# class ViolationDetection(models.Model):
#     detection = models.ForeignKey(Detection, on_delete=models.CASCADE)
#     violation = models.ForeignKey(ViolationMaster, on_delete=models.CASCADE)

class ViolationMaster(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=500)
    fine_amount = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class VehicleViolation(models.Model):
    vehicle = models.ForeignKey(VehicleMonitor, on_delete=models.CASCADE)
    camera = models.ForeignKey(CameraMaster, on_delete=models.CASCADE)
    violation = models.ForeignKey(ViolationMaster, on_delete=models.CASCADE)
    has_paid = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_processed = models.BooleanField(default=False)

    def __str__(self):
        return str(self.vehicle) + ' - ' + str(self.violation)


class Config(models.Model):
    model = models.FileField(max_length=1000)
    fps = models.DecimalField(max_digits=7, decimal_places=3)
    min_threshold = models.DecimalField(max_digits=7, decimal_places=3)
    max_predict_class = models.PositiveIntegerField()

Dashboard/views.py
import datetime
import json

from django.core import serializers
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render

# Create your views here.
from django.views.decorators.csrf import csrf_exempt

from Dashboard.models import Input, Model, ViolationMaster, VehicleViolation, VehicleMonitor
import tensorflow as tf
import cv2

from Dashboard.tasks import vehicle_detection, number_plate_detection


def homepage(request):
    if request.method == 'GET':
        # vehicle_detection()
        all_input = Input.objects.filter(is_processed=False)
        for each_input in all_input:
            # vehicle_detection.apply_async(args=[str(each_input.pk)], queue='feed_tasks')
            vehicle_detection(str(each_input.pk))
            # vehicle_detection(each_input.pk)
        # vehicle_detection.apply_async(queue='vehicle_detection')
        # number_plate_detection.apply_async(queue='number_plate_detection')
        # number_plate_detection()
        # all_input = Input.objects.filter(is_active=True)
        #
        # input_json = {}
        #
        # for each_input in all_input:
        #     input_json[each_input.name] = each_input.model.path

        return render(request, 'html/video_chooser.html')

    if request.method == 'POST':
        video_id = request.POST.get('video_id')
        input = Input.objects.get(id=video_id)
        detection_objs = Model.objects.filter(is_active=True)
        violations = ViolationMaster.objects.filter(is_active=True)
        return render(request, 'html/violation_chooser.html',
                      {'violation_objs': violations, 'detection_objs': detection_objs})


def violation(request):
    return render(request, 'html/violation_chooser.html')


def daywise(request):
    if request.method == 'GET':
        return render(request, 'html/daywise_violation.html')
    else:
        selected_date = datetime.datetime.strptime(request.POST.get('selected_date'), '%d-%m-%Y').date()
        start_timestamp = datetime.datetime.combine(selected_date, datetime.time.min)
        end_timestamp = datetime.datetime.combine(selected_date, datetime.time.max)
        violations = VehicleViolation.objects.filter(timestamp__range=(start_timestamp, end_timestamp))
        if len(violations) == 0:
            message = 'No violations on selected date.'
            return render(request, 'html/daywise_violation.html', {
                'selected_date': selected_date,
                'message': message
            })

        else:
            return render(request, 'html/daywise_violation.html', {
                'selected_date': selected_date,
                'violations': violations
            })


@csrf_exempt
def monitoring(request):
    if request.method == 'GET':
        return render(request, 'html/vehicle_monitoring.html')
    elif request.method == 'POST':
        if request.is_ajax():
            selected_date = datetime.datetime.strptime(request.POST.get('selected_date'), '%m/%d/%Y').date()
            vehicle_number = request.POST.get('vehicle_number')
            start_timestamp = datetime.datetime.combine(selected_date, datetime.time.min)
            end_timestamp = datetime.datetime.combine(selected_date, datetime.time.max)
            results = VehicleMonitor.objects.filter(timestamp__range=(start_timestamp, end_timestamp),
                                                    number_detection__number_plate__number__contains=vehicle_number)

            result_serialized = serializers.serialize('json', results)
            return HttpResponse(result_serialized)

Dashboard/templates/html/daywise_violation.html
{% extends 'new_dashboard.html' %}
{% block style %}
    <style>

    </style>
{% endblock style %}
{% block content %}
    <br>
    <div class="row" style="justify-content: center">
        <h3 class="lead">Daywise Violations</h3>

    </div>
    <div class="row" style="justify-content: center;">
        <form action="{% url 'detection:daywise' %}" method="post" onsubmit="event.preventDefault();"
              id="date_form">
            {% csrf_token %}
            <h4 class="text-muted lead">
                {% if selected_date %}
                    {{ selected_date }}
                {% else %}
                    Select Date
                {% endif %}
                <button id="dateButton" name="date" type="submit" class="btn btn-default">
                    <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 14 16">
                        <path fill-rule="evenodd"
                              d="M13 2h-1v1.5c0 .28-.22.5-.5.5h-2c-.28 0-.5-.22-.5-.5V2H6v1.5c0 .28-.22.5-.5.5h-2c-.28 0-.5-.22-.5-.5V2H2c-.55 0-1 .45-1 1v11c0 .55.45 1 1 1h11c.55 0 1-.45 1-1V3c0-.55-.45-1-1-1zm0 12H2V5h11v9zM5 3H4V1h1v2zm6 0h-1V1h1v2zM6 7H5V6h1v1zm2 0H7V6h1v1zm2 0H9V6h1v1zm2 0h-1V6h1v1zM4 9H3V8h1v1zm2 0H5V8h1v1zm2 0H7V8h1v1zm2 0H9V8h1v1zm2 0h-1V8h1v1zm-8 2H3v-1h1v1zm2 0H5v-1h1v1zm2 0H7v-1h1v1zm2 0H9v-1h1v1zm2 0h-1v-1h1v1zm-8 2H3v-1h1v1zm2 0H5v-1h1v1zm2 0H7v-1h1v1zm2 0H9v-1h1v1z"></path>
                    </svg>
                </button>
                <input type="text" name="selected_date" id="txtDate"
                       style="display: none;" onchange="change_date();">
            </h4>
        </form>
    </div>
    <div class="row" style="justify-content: center;">
        {% if message %}
            <h4 class="display-4">{{ message }}</h4>
        {% elif violations %}
            <table class="table table-responsive table-hover">
                <thead>
                <tr>
                    <th>Vehicle Registration Number</th>
                    <th>Date and Time</th>
                    <th>Location</th>
                    <th>Violation</th>
                    <th>Fine Status</th>
                </tr>
                </thead>
                <tbody>
                {% for row in violations %}
                    <tr>
                        <td>{{ row.vehicle.number }}</td>
                        <td>{{ row.timestamp }}</td>
                        <td>{{ row.camera.location }}</td>
                        <td>{{ row.violation.name }}</td>
                        <td>{{ row.has_paid }}</td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>

        {% endif %}
    </div>
    <script>

        $('#txtDate').datepicker({
            format: 'dd-mm-yyyy',

        });
        $('#dateButton').click(function () {
            $('#txtDate').show().focus().hide();
        });


        function change_date() {
            var form = document.getElementById('date_form');
            var input = document.createElement('input');
            input.setAttribute('name', 'GO');
            input.setAttribute('type', 'hidden');
            form.appendChild(input);
            form.submit();
        }

    </script>
{% endblock content %}

Dashboard/templates/html/vehicle_monitoring.html
{% extends 'new_dashboard.html' %}
{% block style %}
    <style>

    </style>
{% endblock style %}
{% block content %}
    <br>
    <div class="row" style="justify-content: center">
        <h3 class="lead">Vehicle Monitoring</h3>
    </div>

    <form action="#">
        <div class="row" style="justify-content: center">
            <div class="col-md-6">
                <div class="row text-muted" style="justify-content: center">
                    Search with Date
                </div>
                <div class="row" style="justify-content: center">

                    <input name="date_search" id="date_search" onchange="search()"/>

                </div>
            </div>
            <div class="col-md-6">
                <div class="row text-muted" style="justify-content: center">
                    Search with Vehicle Number
                </div>
                <div class="row" style="justify-content: center">
                    <input name="vehicle_number" id="vehicle_number" onkeyup="search()">
                </div>
            </div>
        </div>
    </form>

    <script>
        $('#date_search').datepicker({
            format: 'dd-mm-yyyy',
        });

        function search() {
            let date = document.getElementById('date_search').value;
            alert(date);
            let vehicle_number = document.getElementById('vehicle_number').value;

            $.ajax({
                url: '{% url 'detection:monitoring' %}',
                data: {
                    'selected_date': date,
                    'vehicle_number': vehicle_number
                },
                type: 'POST',
                success: function (data) {
                    console.log(data);
                }
            });
        }
    </script>

{% endblock content %}

Dashboard/templates/html/video_chooser.html
{% extends 'dashboard_base.html' %}
{% block style %}
    <style>

    </style>
{% endblock style %}
{% block content %}
    <br>
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <div class="card text-center">
                <div class="card-header">
                    <h3 class="card-title">Select Video</h3>
                </div>
                <div class="card-body">
                    <form action="{% url 'detection:homepage' %}" method="post">
                    {% csrf_token %}
                        <div class="row">
                            {% for i in all_input %}
                                <div class="col-md-4">
                                    <input type="radio" name="video_id" id="video_{{ i.pk }}" value="{{ i.pk }}"/>
                                    <label for="r1">
                                        <video width="100%" controls="controls">
                                            <source src="{{ i.model }}" type="video/mp4">
                                        </video>
                                    </label>
                                </div>
                            {% endfor %}
                        </div>
                        <input type="submit" class="btn btn-primary">
                    </form>

                    {#                    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>#}
                    {#                    <a href="#" class="btn btn-primary">Go somewhere</a>#}
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

Dashboard/templates/html/violation_chooser.html
{% extends 'dashboard_base.html' %}
{% block style %}
    <style>

    </style>
{% endblock style %}
{% block content %}
    <br>
    <form action="{% url 'detection:violation' %}" method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-4 offset-md-1">
                <div class="card text-center">
                    <div class="card-header">
                        <h3 class="card-title">Select Violation</h3>
                    </div>
                    <div class="card-body">
                        {% for i in violation_objs %}
                            <input type="radio" name="violation" value="{{ i.pk }}" id="violation_{{ i.pk }}"
                                   onclick="filterSelection('{{ i.name }}')">
                            <label for="violation_{{ id.pk }}"
                                   onclick="filterSelection('{{ i.name }}')">{{ i.name }}</label><br>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="col-md-4 offset-md-1">
                <div class="card text-center">
                    <div class="card-header">
                        <h3 class="card-title">Select Model</h3>
                    </div>
                    <div class="card-body" id="model_card">

                        <p class="card-text" id="initial_message">Select any model first!</p>

                        <div id="model_list" style="display: none;">
                            {% for i in detection_objs %}
                                <div class="{{ i.model_type }}" style="display: none;">
                                    <input type="radio" name="model" value=" {{ i.pk }}" id="model_{{ i.pk }}">
                                    <label for="model_{{ i.pk }}">{{ i.model_name }}</label>
                                </div>
                            {% endfor %}
                        </div>

                    </div>
                </div>
            </div>


        </div>
        <div class="row">
            <div class="offset-md-5 col-md-1">
                <input type="submit" class="btn btn-primary">
            </div>
        </div>
    </form>


    <script>
        function filterSelection(c) {
            document.getElementById('initial_message').style.display = 'none';

            parent_div = document.getElementById('model_list').style.display = 'block';

            var children = [].slice.call(document.getElementById('model_list').getElementsByTagName('div'), 0);
            var elements = new Array(children.length);
            var arrayLength = children.length;
            for (var i = 0; i < arrayLength; i++) {
                if (children[i].getAttribute("class") === c) {
                    children[i].style.display = 'block';
                } else {
                    children[i].style.display = 'none';
                }
            }

        }
    </script>
{% endblock content %}